name: Validate HTML

on:
  push:
    branches:
      - master

jobs:
  html_validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate HTML
      uses: cyb3r-jak3/html-validator-action@v1
      with:
        folder: "./public"
