name: Validate HTML

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  html_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run W3C HTML Validator
        uses: nickcolley/w3c-html-validator-action@v1.0.0
        with:
          file-path: '/demo-gitaction'  # Checks the entire repository for HTML files
